const pageActionTypes = {
  // SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  ADD_MUSHAF: "ADD_MUSHAF",
  SET_CURRENT_MUSHAF: "SET_CURRENT_MUSHAF",
  SET_CURRENT_MUSHAF_PAGE: "SET_CURRENT_MUSHAF_PAGE",
  DELETE_INSTANCE: "DELETE_INSTANCE",
  SET_MUSHAFS: "SET_MUSHAFS",
  ADD_BOOKMARK: "ADD_BOOKMARK"
};

export default pageActionTypes;
